### ISSUE TITLE
Error: Could not execute posix command: Invalid group

### ISSUE THREAD

**Issue by jingweno** [boxen/puppet-homebrew#20]
I set up boxen using my company's network and everything works fine. But when I run it at home, it has the following errors related to group permission. It's related to the issue here: https://github.com/boxen/our-boxen/issues/235.

```
Error: /Stage[main]/Imagemagick/Package[boxen/brews/little-cms2]/ensure: change from absent to 2.4-boxen1 failed: Could not update: Execution of 'brew info boxen/brews/little-cms2' returned 1: Error: Could not execute posix command: Invalid group: 168357174
/opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/log/destinations.rb:94:in `flush': Bad file descriptor - /opt/boxen/repo/log/boxen.log (Errno::EBADF)
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/log/destinations.rb:94:in `handle'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/log.rb:156:in `newmessage'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:322:in `threadlock'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:72:in `synchronize_on'
	from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/sync.rb:230:in `synchronize'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:72:in `synchronize_on'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:322:in `threadlock'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/log.rb:155:in `newmessage'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/log.rb:154:in `each'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/log.rb:154:in `newmessage'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/log.rb:242:in `initialize'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/log.rb:82:in `new'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/log.rb:82:in `create'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/logging.rb:8:in `send_log'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/logging.rb:15:in `err'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/logging.rb:27:in `log_exception'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/execution.rb:226:in `execute_posix'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:314:in `call'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:314:in `safe_posix_fork'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:307:in `fork'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:307:in `safe_posix_fork'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/execution.rb:191:in `execute_posix'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/execution.rb:143:in `execute'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/provider.rb:118:in `execute'
	from /opt/boxen/repo/shared/boxen/lib/puppet/provider/package/homebrew.rb:92:in `version_defined?'
	from /opt/boxen/repo/shared/boxen/lib/puppet/provider/package/homebrew.rb:56:in `install'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/type/package.rb:105
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/property.rb:205:in `instance_eval'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/property.rb:205:in `call_valuemethod'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/property.rb:489:in `set'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/property.rb:572:in `sync'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/transaction/resource_harness.rb:114:in `apply_parameter'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/transaction/resource_harness.rb:56:in `perform_changes'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/transaction/resource_harness.rb:133:in `evaluate'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/transaction.rb:48:in `apply'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/transaction.rb:83:in `eval_resource'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/transaction.rb:103:in `evaluate'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:351:in `thinmark'
	from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:350:in `thinmark'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/transaction.rb:103:in `evaluate'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/transaction.rb:382:in `traverse'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/transaction.rb:98:in `evaluate'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/resource/catalog.rb:144:in `apply'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/configurer.rb:122:in `apply_catalog'
	from /opt/boxen/repo/shared/boxen/lib/puppet/provider/package/hax.rb:12:in `benchmark'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/configurer.rb:121:in `apply_catalog'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/configurer.rb:179:in `run'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/application/apply.rb:265:in `apply_catalog'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/application/apply.rb:213:in `main'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/application/apply.rb:146:in `run_command'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `run'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/application.rb:456:in `plugin_hook'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `run'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util.rb:504:in `exit_on_fail'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `run'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/command_line.rb:132:in `run'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/lib/puppet/util/command_line.rb:86:in `execute'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/puppet-3.1.1/bin/puppet:4
	from /opt/boxen/repo/bin/puppet:16:in `load'
	from /opt/boxen/repo/bin/puppet:16
```

**Comment by mikemcquaid** [comment]
Closing as supposedly fixed by https://github.com/boxen/our-boxen/pull/581.
