### ISSUE TITLE
Error: Execution of 'brew update' returned 1: Error: Cowardly refusing to 'sudo brew update'

### ISSUE THREAD

**Issue by salimane** [boxen/puppet-homebrew#91]
After updating brew 
```
salimane at Salimanes-MacBook-Pro (git:salimane.com)  [docker-vm R] in ~/
± brew update                                                                     
==> Migrating Homebrew to v0.9.9
From https://github.com/Homebrew/brew
 + 6146a1c...fbc5fc3 master     -> origin/master  (forced update)
HEAD is now at fbc5fc3 Mention the haskell-platform cask
Already up-to-date.
```

while running boxen, I started getting : 
```
[1;31mError: Execution of 'brew update' returned 1: Error: Cowardly refusing to 'sudo brew update'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
Notice: /Package[docker]: Dependency Homebrew_repo[/usr/local] has failures: true
```

Everything was running without errors a few days ago.

@mikemcquaid any idea  ?

Thanks

**Comment by jacobbednarz** [comment]
I also seen this problem earlier today. Does it have anything to do with the split of homebrew into separate repositories?

**Comment by jacobbednarz** [comment]
I'e managed to fix this locally by taking the following steps:

- Clone boxen/puppet-homebrew locally
- Update [`manifests/config.pp`](https://github.com/boxen/puppet-homebrew/blob/master/manifests/config.pp#L19) to use the minimum version of `fbc5fc3e92587b47ddd8d8a97eb8e3a138d72957` instead of `e90b6e9ded2fd2c73a4e0d93f5dbc5b075a61b7c `.
- Point your Puppetfile at the local version of the `puppet-homebrew` repository.
- Rerun puppet-librarian

  ```
  $ bundle exec librarian-puppet install --clean
  ```
- Run Boxen.

To me this suggests something upstream is a bit off and requires some investigation. I'll have a look today but @mikemcquaid would probably be in a better position to identify the potential issue here as he would be better across the split.

**Comment by mikemcquaid** [comment]
Yes, this is almost certainly related to the splitting of repositories. I'm not personally using Boxen any more so is there any chance you could submit a PR @jacobbednarz?

**Comment by jacobbednarz** [comment]
No worries at all. I'll take a stab at fixing the problem but in the meantime I'll roll Boxen back to using the working version so this doesn't keep catching people out.

**Comment by jacobbednarz** [comment]
Proposed short term fix in #92 but will have a deeper dig into how we can move forward on this too.

**Comment by salimane** [comment]
@jacobbednarz @mikemcquaid check #93 as the real fix

**Comment by agustinvinao** [comment]
Im still have this problem, I've tried @jacobbednarz  solution without success.

Any idea how to fix it?

```
Error: Execution of 'brew update' returned 1: Error: Cowardly refusing to 'sudo brew update'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
Error: /Stage[main]/Homebrew::Repo/Homebrew_repo[/usr/local]/min_revision: change from d5085edce0b5482771c66cfe3e2c013ee3ca90f6 to e90b6e9ded2fd2c73a4e0d93f5dbc5b075a61b7c failed: Execution of 'brew update' returned 1: Error: Cowardly refusing to 'sudo brew update'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
```

**Comment by jacobbednarz** [comment]
@agustinvinao Are you running `puppet-homebrew` 2.0.2 in your forked version of our-boxen?

**Comment by agustinvinao** [comment]
@jacobbednarz  yes, in my puppetfile I have 

```
github "homebrew",    "2.0.2"
```

**Comment by jacobbednarz** [comment]
And you've updated all the dependencies via `librarian-puppet`? Or you just updated the Puppetfile? Did you merge into your fork from `boxen/our-boxen`?

**Comment by agustinvinao** [comment]
I did a new update of all and now I have some dependencies issues when I try to run boxen from scratch

```
[Librarian]     Checking boxen/3.11.0 <boxen/puppet-boxen>
[Librarian]       Conflict between boxen/3.11.0 <boxen/puppet-boxen> and boxen (= 3.11.1) <boxen/puppet-boxen>
[Librarian]       Backtracking from boxen/3.11.0 <boxen/puppet-boxen>
[Librarian]     Checking boxen/3.10.4 <boxen/puppet-boxen>
[Librarian]       Conflict between boxen/3.10.4 <boxen/puppet-boxen> and boxen (= 3.11.1) <boxen/puppet-boxen>
[Librarian]       Backtracking from boxen/3.10.4 <boxen/puppet-boxen>
[Librarian]     Checking boxen/3.10.3 <boxen/puppet-boxen>
[Librarian]       Conflict between boxen/3.10.3 <boxen/puppet-boxen> and boxen (= 3.11.1) <boxen/puppet-boxen>
[Librarian]       Backtracking from boxen/3.10.3 <boxen/puppet-boxen>
[Librarian]     Checking boxen/3.10.2 <boxen/puppet-boxen>
....
```

and fails without resolve boxen, now im trying to fix it.

**Comment by jacobbednarz** [comment]
I'd recommend trying to merge in the upstream fork (if you aren't already) as it won't require you to have run `librarian-puppet` since it will all be local to the repository.

**Comment by agustinvinao** [comment]
I've dont it and after merged that I have this dependency problem

```
Could not resolve the dependencies.
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/persist_resolution_mixin.rb:11:in `persist_resolution'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:27:in `run'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/cli.rb:67:in `install'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/bin/librarian-puppet:7:in `<top (required)>'
/opt/boxen/repo/bin/librarian-puppet:16:in `load'
/opt/boxen/repo/bin/librarian-puppet:16:in `<main>'
Can't run Puppet, fetching dependencies with librarian failed.
```

**Comment by jacobbednarz** [comment]
can you paste your `Puppetfile`?

**Comment by agustinvinao** [comment]
here is:
```
# This file manages Puppet module dependencies.
#
# It works a lot like Bundler. We provide some core modules by
# default. This ensures at least the ability to construct a basic
# environment.

# Shortcut for a module from GitHub's boxen organization
def github(name, *args)
  options ||= if args.last.is_a? Hash
    args.last
  else
    {}
  end

  if path = options.delete(:path)
    mod name, :path => path
  else
    version = args.first
    options[:repo] ||= "boxen/puppet-#{name}"
    mod name, version, :github_tarball => options[:repo]
  end
end

# Shortcut for a module under development
def dev(name, *args)
  mod "puppet-#{name}", :path => "#{ENV['HOME']}/src/boxen/puppet-#{name}"
end

# Includes many of our custom types and providers, as well as global
# config. Required.

github "boxen", "3.11.1"

# Support for default hiera data in modules

github "module_data", "0.0.4", :repo => "ripienaar/puppet-module-data"

# Core modules for a basic development environment. You can replace
# some/most of these if you want, but it's not recommended.

github "brewcask",    "0.0.6"
github "dnsmasq",     "2.0.1"
github "foreman",     "1.2.0"
github "gcc",         "3.0.2"
github "git",         "2.7.92"
github "go",          "2.1.0"
github "homebrew",    "2.0.2"
github "hub",         "1.4.1"
github "inifile",     "1.4.1", :repo => "puppetlabs/puppetlabs-inifile"
github "nginx",       "1.6.0"
github "nodejs",      "5.0.0"
github "openssl",     "1.0.0"
github "phantomjs",   "3.0.0"
github "pkgconfig",   "1.0.0"
github "repository",  "2.4.1"
github "ruby",        "8.5.4"
github "stdlib",      "4.7.0", :repo => "puppetlabs/puppetlabs-stdlib"
github "sudo",        "1.0.0"
github "xquartz",     "1.2.1"

# Optional/custom modules. There are tons available at
# https://github.com/boxen.
github "elasticsearch",           "2.8.0" #"1.0.1"
github "mysql",                   "2.0.1"
github "postgresql",              "4.0.1"
github "redis",                   "3.1.0"
github "sysctl",                  "1.0.1"

github "chrome",                  "1.1.0"
github "dropbox",                 "1.1.0"
github "handbrake",               "1.0.1"
github "osx",                     "2.0.8"
github "sublime_text_2",          "1.1.2"
github "vlc",                     "1.1.0"
github "wget",                    "1.0.1"
github "colloquy",                "1.0.0"
github "harvest",                 "1.0.2"
github "googledrive",             "1.0.2"
github "statsd",                  "1.0.3"
github "ctags",                   "1.0.0"
github "mongodb",                 "1.5.0"
github "sequel_pro",              "1.0.1"
github "postgresapp",             "1.0.0"
github "skype",                   "1.1.0"
github "mou",                     "1.1.0"
github "tmux",                    "1.0.2"
github "iterm2",                  "1.2.5"
github "firefox",                 "1.2.3"
github "autoconf",                "1.0.0"
github "libtool",                 "1.0.0"
github "pkgconfig",               "1.0.0"
github "pcre",                    "1.0.0"
github "java",                    "1.8.4"
github "linkinus",                "1.0.3"
github "libpng",                  "1.0.0"
github "zookeeper",               "1.0.4"
# github "python",                  "2.0.1"
github "ohmyzsh",                 "0.1.2", :repo => "acme/puppet-acme-oh-my-zsh"
github "archiver",                "0.0.1", :repo => "am/puppet-archiver"
github "python",                  "3.0.2", :repo => "mloberg/puppet-python"
github "the_silver_searcher",     "0.0.3", :repo => "agustinvinao/puppet-the_silver_searcher"
github "reattachtousernamespace", "0.0.2", :repo => "agustinvinao/puppet-reattach-to-user-namespace"
github "colordiff",               "0.0.1", :repo => "agustinvinao/puppet-colordiff"
github "kafka",                   "0.0.1", :repo => "agustinvinao/puppet-kafka"

```

**Comment by agustinvinao** [comment]
I've fixed the dependencies issue but I have the 'bre update' issue again:

```
➜  repo git:(master) ✗ clear && ./script/boxen
--> Preparing to auto-update...
--> Skipping auto-update, because you've got uncommitted changes:
/opt/boxen/repo/shared/boxen/lib/facter/boxen_facts_d.rb:11: warning: already initialized constant BoxenFactsDirectoryLoader::EXTERNAL_FACT_WEIGHT
/opt/boxen/repo/modules/boxen/lib/facter/boxen_facts_d.rb:11: warning: previous definition of EXTERNAL_FACT_WEIGHT was here
Notice: Compiled catalog for av-macbook-pro.local in environment production in 3.54 seconds
Error: Execution of 'brew update' returned 1: Error: Cowardly refusing to 'sudo brew update'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
Error: /Stage[main]/Homebrew::Repo/Homebrew_repo[/usr/local]/min_revision: change from d5085edce0b5482771c66cfe3e2c013ee3ca90f6 to e90b6e9ded2fd2c73a4e0d93f5dbc5b075a61b7c failed: Execution of 'brew update' returned 1: Error: Cowardly refusing to 'sudo brew update'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
Notice: /Package[libtool]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[libtool]: Skipping because of failed dependencies
Notice: /Package[boxen/brews/hub]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[boxen/brews/hub]: Skipping because of failed dependencies
Notice: /Package[boxen/brews/elasticsearch]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[boxen/brews/elasticsearch]: Skipping because of failed dependencies
Notice: /Package[boxen/brews/mysql]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[boxen/brews/mysql]: Skipping because of failed dependencies
Notice: /Package[boxen/brews/gcc5]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[boxen/brews/gcc5]: Skipping because of failed dependencies
Notice: /Package[Skype]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[Skype]: Skipping because of failed dependencies
Notice: /Package[wget]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[wget]: Skipping because of failed dependencies
Notice: /Package[jre-7u21.dmg]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[jre-7u21.dmg]: Skipping because of failed dependencies
Notice: /Package[boxen/brews/nginx]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[boxen/brews/nginx]: Skipping because of failed dependencies
Notice: /Package[colordiff]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[colordiff]: Skipping because of failed dependencies
Notice: /Package[jdk-7u21.dmg]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[jdk-7u21.dmg]: Skipping because of failed dependencies
Notice: /Package[XQuartz]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[XQuartz]: Skipping because of failed dependencies
Notice: /Package[SublimeText2]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[SublimeText2]: Skipping because of failed dependencies
Notice: /Package[Harvest]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[Harvest]: Skipping because of failed dependencies
Notice: /Package[pcre]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[pcre]: Skipping because of failed dependencies
Notice: /Package[boxen/brews/mongodb]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[boxen/brews/mongodb]: Skipping because of failed dependencies
Notice: /Stage[main]/Mongodb/Service[dev.mongodb]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Stage[main]/Mongodb/Service[dev.mongodb]: Skipping because of failed dependencies
Notice: /Package[Dropbox]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[Dropbox]: Skipping because of failed dependencies
Notice: /Package[the_silver_searcher]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[the_silver_searcher]: Skipping because of failed dependencies
Notice: /Package[Chrome]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[Chrome]: Skipping because of failed dependencies
Notice: /Package[HandBrake]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[HandBrake]: Skipping because of failed dependencies
Notice: /Package[Colloquy]: Dependency Homebrew_repo[/usr/local] has failures: true
Warning: /Package[Colloquy]: Skipping because of failed dependencies
```

and it has a more lines like this

**Comment by jacobbednarz** [comment]
The dependency issue looks to be caused by [`puppet-osx`](https://github.com/boxen/puppet-osx/). Removing this allows `librarian-puppet` to complete.

**Comment by agustinvinao** [comment]
yes, now all dependencies works ok, it was my error in the revision number.
After that fix, now I have the brew update error again, the strange thing is I can run "brew update" manually and runs ok

**Comment by jacobbednarz** [comment]
Are you using `/usr/local` for your homebrew setup? Did you have homebrew pointing to the old directory?

**Comment by agustinvinao** [comment]
In my boxen setup, facts.d/example.yaml I have:

```
homebrew_root: /usr/local
```
and when I run brew config this is the output:
```
➜  repo git:(master) ✗ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d7aa0c0335dd67e4151503f3a29d7089c57059c3
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a2bdeba786221da4a629998bebf62990b845a4de
Core tap last commit: 19 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.11.4-x86_64
Xcode: 7.3
CLT: 7.3.0.0.1.1457485338
Clang: 7.3 build 703
X11: 2.7.4 => /opt/X11
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /opt/boxen/pyenv/shims/python => /opt/python/3.5.0/bin/python3.5
Ruby: /opt/boxen/rbenv/shims/ruby => /opt/rubies/2.2.4/bin/ruby
Java: 1.7.0_21
➜  repo git:(master) ✗ which brew
/usr/local/bin/brew
```
I put the output for 'which brew' too

**Comment by jacobbednarz** [comment]
can you try it without defining `homebrew_root` as a fact? I'm running it under `/opt/boxen` so perhaps related to a permissions issue?

**Comment by agustinvinao** [comment]
It took a some time, but, it install all ok but after install if I run "boxen" I got the "brew update" error

**Comment by salimane** [comment]
@agustinvinao , in the logs you pasted above, you have 
```
Error: /Stage[main]/Homebrew::Repo/Homebrew_repo[/usr/local]/min_revision: change from d5085edce0b5482771c66cfe3e2c013ee3ca90f6 to e90b6e9ded2fd2c73a4e0d93f5dbc5b075a61b7c failed: Execution of 'brew update' returned 1: Error: Cowardly refusing to 'sudo brew update'
```

This is still not ``puppet-homebrew 2.0.2`` 

could you manually run in your ``our-boxen`` folder
```
librarian-puppet update --verbose
```

**Comment by agustinvinao** [comment]
After 

```
librarian-puppet update --verbose
```

I'm still have
```
Error: /Stage[main]/Homebrew::Repo/Homebrew_repo[/opt/boxen/homebrew]/min_revision: change from d7aa0c0335dd67e4151503f3a29d7089c57059c3 to e90b6e9ded2fd2c73a4e0d93f5dbc5b075a61b7c failed: Execution of 'brew update' returned 1: Error: Cowardly refusing to 'sudo brew update'
```

any idea why it should be?
